
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: photos-scheil-one-tls
  namespace: traefik
spec:
  secretName: photos-scheil-one-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: photos.scheil.one
  dnsNames:
    - photos.scheil.one
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
