apiVersion: v1
kind: Service
metadata:
  name: homeassistant-clusterip
spec:
  type: ClusterIP
  ports:
  - port: 8123
    targetPort: 8123
---
apiVersion: v1
kind: Endpoints
metadata:
  name: homeassistant-clusterip
subsets:
- addresses:
  - ip: 192.168.0.205
  ports:
  - port: 8123
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-scheil-one-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: traefik-redirect-scheme@kubernetescrd
  tls:
  - hosts:
    - home.scheil.one
    secretName: homeassistant-tls
  rules:
  - host: home.scheil.one
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homeassistant-clusterip
            port:
              number: 8123