---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: traefik
      version: "^35.0.0" # Use a suitable version, check Traefik Helm chart releases
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 1h
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    ports:
      web:
        port: 80
      websecure:
        port: 443
    entryPoints:
      web:
        address: ":80/tcp"
        http:
          redirections:
            entryPoint:
              to: "websecure"
              scheme: "https"
              permanent: true
      websecure:
        address: ":443/tcp"
        tls:
          enabled: true

