---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: traefik
      version: "^36.3.0" # Use a suitable version, check Traefik Helm chart releases
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 1h
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    ports:
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true
    providers:
      kubernetesIngress:
        ingressClass: traefik
        publishedService:
          enabled: true
      kubernetesCRD:
        enabled: true
        namespaces:
          - "" # This tells Traefik to watch all namespaces for CRDs
        allowCrossNamespace: true
        allowExternalNameServices: true
    ingressRoute:
      dashboard:
        enabled: true
        entryPoints:
          - websecure
        router:
          tls:
            certResolver: letsencrypt
    certResolvers:
      letsencrypt:
        email: matthis@scheil.one
        storage: /data/acme.json
        httpChallenge:
          entryPoint: web
