---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: traefik
      version: "^35.0.0" # Use a suitable version, check Traefik Helm chart releases
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 1h
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  dependsOn:
    - name: traefik
      namespace: flux-system
  values:
    values:
    providers:
      kubernetesIngress:
        ingressClass: traefik
        publishedService:
          enabled: true
      kubernetesCRD:
        enabled: true
        namespaces:
          - "" # This tells Traefik to watch all namespaces for CRDs
        allowCrossNamespace: true
        allowExternalNameServices: true
    certResolvers:
      letsencrypt:
        email: matthis@scheil.one
        storage: /data/acme.json
        httpChallenge:
          entryPoint: web
    additionalArguments:
      - --entrypoints.web.http.redirections.entrypoint.disable=true

