
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: files-scheil-one-tls
  namespace: traefik
spec:
  secretName: files-scheil-one-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: files.scheil.one
  dnsNames:
    - files.scheil.one
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
