---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-namespace
  namespace: flux-system
spec:
  interval: 1h
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/k8s-talos # Path to the directory containing traefik-namespace.yaml
  healthChecks:
    - apiVersion: v1
      kind: Namespace
      name: traefik
