
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: "25.0.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 1m
  values:
    service:
      type: LoadBalancer
    deployment:
      podSecurityContext:
        seccompProfile:
          type: RuntimeDefault
    # Enable ACME for Let's Encrypt
    certificatesResolvers:
      letsencrypt-prod:
        acme:
          email: your-email@example.com # <--- IMPORTANT: Replace with your actual email
          storage: /data/acme.json
          httpChallenge:
            entryPoint: web
    # Configure entrypoints
    entryPoints:
      web:
        address: ":80"
      websecure:
        address: ":443"
        http:
          tls:
            certResolver: letsencrypt-prod
