
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: "25.0.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 1m
  values:
    service:
      type: LoadBalancer
    deployment:
      podSecurityContext:
        seccompProfile:
          type: RuntimeDefault
    # Explicitly disable the new ACME feature causing conflicts
    additionalArguments:
      - "--certificatesresolvers.myresolver.acme.storage=/data/acme.json"
      - "--certificatesresolvers.myresolver.acme.email=your-email@example.com"
      - "--entrypoints.websecure.http.tls.certresolver=myresolver"
