apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: "36.3.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 1m
  values:
    service:
      type: LoadBalancer
    deployment:
      podSecurityContext:
        seccompProfile:
          type: RuntimeDefault
    # Configure entrypoints
    entryPoints:
      web:
        address: ":80"
      websecure:
        address: ":443"
        http:
          tls:
            certResolver: letsencrypt-prod
            domains:
              - main: "scheil.one"
                sans:
                  - "*.scheil.one"
    # Configure persistence for ACME data
    persistence:
      enabled: true
      name: acme-data
      size: 1Gi
      storageClassName: longhorn
      accessMode: ReadWriteOnce
