apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: matthis@scheil.one
    privateKeySecretRef:
      name: letsencrypt-prod-issuer-account-key
    solvers:
    - dns01:
        webhook:
          groupName: acme.scheil.one
          solverName: hetzner
          config:
            apiKeySecretRef:
              name: hetzner-secret
              key: api-token