# apiVersion: v1
# kind: Service
# metadata:
#   name: uptime-clusterip
# spec:
#   type: ClusterIP
#   ports:
#   - port: 3001
#     targetPort: 3001
# ---
# apiVersion: v1
# kind: Endpoints
# metadata:
#   name: uptime-clusterip
# subsets:
# - addresses:
#   - ip: 192.168.0.10
#   ports:
#   - port: 3001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-scheil-one-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: traefik-redirect-scheme@kubernetescrd
spec:
  ingressClassName: traefik
  
  tls:
  - hosts:
    - uptime.scheil.one
    secretName: uptime-tls
  rules:
  - host: uptime.scheil.one
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: uptime-clusterip
            port:
              number: 3001