
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-scheil-one-tls
  namespace: traefik
spec:
  secretName: home-scheil-one-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: home.scheil.one
  dnsNames:
    - home.scheil.one
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
