apiVersion: v1
kind: Service
metadata:
  name: paperless-clusterip
spec:
  type: ClusterIP
  ports:
  - port: 8181
    targetPort: 8181
---
apiVersion: v1
kind: Endpoints
metadata:
  name: paperless-clusterip
subsets:
- addresses:
  - ip: 192.168.0.10
  ports:
  - port: 8181
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paperless-scheil-one-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - paperless.scheil.one
    secretName: paperless-tls
  rules:
  - host: paperless.scheil.one
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: paperless-clusterip
            port:
              number: 8181