apiVersion: v1
kind: Service
metadata:
  name: jellyfin-external
  namespace: default
spec:
  type: ExternalName
  externalName: 192.168.0.95
  ports:
  - port: 8096
    targetPort: 8096
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: media-scheil-one-ingressroute
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`media.scheil.one`)
      kind: Rule
      services:
        - name: jellyfin-external
          port: 8096
      middlewares:
        - name: traefik-redirect-scheme@kubernetescrd
  tls:
    secretName: jellyfin-tls
