apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crowdsec
  namespace: crowdsec
spec:
  interval: 5m
  chart:
    spec:
      chart: crowdsec
      version: "0.7.3"
      sourceRef:
        kind: HelmRepository
        name: crowdsec
        namespace: flux-system
      interval: 1m
  values:
    agent:
      acquisition:
        - podName: traefik-*
          namespace: traefik
          program: traefik