
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: media-scheil-one-tls
  namespace: traefik
spec:
  secretName: media-scheil-one-tls # Force Flux reconciliation
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: media.scheil.one
  dnsNames:
    - media.scheil.one
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
