apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k8s-talos-apps
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/k8s-talos/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
