apiVersion: v1
kind: Service
metadata:
  name: metube-clusterip
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 8087
    targetPort: 8087
---
apiVersion: v1
kind: Endpoints
metadata:
  name: metube-clusterip
  namespace: default
subsets:
- addresses:
  - ip: 192.168.0.10
  ports:
  - port: 8087
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metube-scheil-one-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: traefik-redirect-scheme@kubernetescrd
spec:
  ingressClassName: traefik
  
  tls:
  - hosts:
    - metube.scheil.one
    secretName: metube-tls
  rules:
  - host: metube.scheil.one
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: metube-clusterip
            port:
              number: 8087