apiVersion: v1
kind: Service
metadata:
  name: photos-clusterip
spec:
  type: ClusterIP
  ports:
  - port: 2283
    targetPort: 2283
---
apiVersion: v1
kind: Endpoints
metadata:
  name: photos-clusterip
subsets:
- addresses:
  - ip: 192.168.0.10
  ports:
  - port: 2283
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: photos-scheil-one-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - photos.scheil.one
    secretName: photos-tls
  rules:
  - host: photos.scheil.one
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: photos-clusterip
            port:
              number: 2283